---
title: "day-17"
author: "Catherine Rauch"
date: "8/31/2020"
output: html_document
---

```{r setup, include=FALSE}

library(rgdal)
library(sf)
library(tidyverse)

```


```{r pressure, warning=FALSE, message=FALSE}

# read uscities.csv data into R, make it a sf object, and filter to Goleta
goletadata <- read_csv("~/github/geog-176A-labs/data/uscities.csv") %>%
  st_as_sf(coords = c("lng", "lat"), crs = 4326) %>%
  filter(city == "Goleta") %>% 
  # transform to CRS:5070 and create a 5 km buffer
  st_transform(5070) %>% 
  st_buffer(5000) %>%
  # get bounding box of buffer and make bbox object a sfc and then sf object
  st_bbox() %>% 
  st_as_sfc() %>% 
  st_as_sf()



# crop elevation object to bounding box
elevationobj <- elevatr::get_elev_raster(goletadata, z = 12) %>% 
                raster::crop(goletadata)
 
raster::writeRaster(elevationobj, filename = "goleta-elev.tif", overwrite = TRUE)


# plot raster and describe properties
plot(raster::raster("goleta-elev.tif"))
raster::raster("goleta-elev.tif")


```
